# Generated by Django 4.2.7 on 2024-02-16 18:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0003_alter_profile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='subscribers',
            field=models.ManyToManyField(related_name='subscribed_profiles', to=settings.AUTH_USER_MODEL),
        ),
    ]
